[package]
name = "krkrz_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
krkrz_core.workspace = true
krkrz_assets.workspace = true
krkrz_tjs.workspace = true
krkrz_kag.workspace = true
krkrz_runtime.workspace = true
winit = "0.30.13"
wgpu = "0.20.1"
pollster = "0.3.0"
env_logger = "0.11"
cpal = "0.15.3"

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "krkrz_engine"
path = "src/engine.rs"

[[bin]]
name = "krkrz_tool"
path = "src/tool.rs"
