[package]
name = "na_mpeg2_decoder"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "Rust MPEG-1/2 decoder vendored from siglus_rs"

[dependencies]
thiserror.workspace = true
log.workspace = true
byteorder.workspace = true
symphonia.workspace = true
oxideav-ac3.workspace = true
oxideav-core.workspace = true

[lints.rust]
unused = "allow"
non_upper_case_globals = "allow"

[lints.clippy]
all = "allow"
