[package]
name = "krkrz_runtime"
version.workspace = true
edition.workspace = true
license = "MIT AND BSD-3-Clause"

[dependencies]
na_mpeg2_decoder.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
krkrz_core.workspace = true
krkrz_assets.workspace = true
krkrz_tjs.workspace = true
krkrz_kag.workspace = true
encoding_rs.workspace = true
tempfile.workspace = true
sha2.workspace = true
realfft.workspace = true
uuid.workspace = true
skrifa.workspace = true
zeno.workspace = true
fast_image_resize.workspace = true
tiny-skia.workspace = true
lru.workspace = true
image.workspace = true
imageproc.workspace = true
rubato.workspace = true
audioadapter-buffers.workspace = true
dirs.workspace = true
fontdb.workspace = true
