[package]
name = "krkrz_assets"
version.workspace = true
edition.workspace = true
license = "MIT AND BSD-3-Clause"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
flate2.workspace = true
adler2.workspace = true
encoding_rs.workspace = true
krkrz_core.workspace = true
image = { workspace = true, features = ["png", "jpeg", "bmp", "ico"] }
libtlg-rs.workspace = true
png.workspace = true
lewton.workspace = true
pelite.workspace = true
hound.workspace = true
lru.workspace = true
bitstream-io.workspace = true

[dev-dependencies]
tempfile.workspace = true
tlg-rs.workspace = true
