// Word table from Kirikiri tjs2/syntax/dp_wordtable.txt (BSD-3-Clause).
fn word(word: &str) -> Option<Token> {
    Some(match word {
        "jst" | "awsst" | "kst" | "wdt" => Token::Zone(900),
        "ut" | "utc" | "gmt" | "z" | "wet" => Token::Zone(0),
        "est" | "cdt" => Token::Zone(-500),
        "edt" | "ast" => Token::Zone(-400),
        "cst" | "mdt" => Token::Zone(-600),
        "mst" | "pdt" => Token::Zone(-700),
        "pst" | "ydt" => Token::Zone(-800),
        "a" | "wat" => Token::Zone(-100),
        "m" | "idlw" => Token::Zone(-1200),
        "n" | "bst" | "cet" | "dnt" | "fst" | "met" | "mewt" | "mez" | "nor" | "set" | "swt" | "wetdst" => Token::Zone(100),
        "y" | "idle" | "nzst" | "nzt" => Token::Zone(1200),
        "nzdt" => Token::Zone(1300),
        "aesst" => Token::Zone(1100),
        "acsst" | "cadt" | "sadt" => Token::Zone(1030),
        "aest" | "east" | "gst" | "ligt" => Token::Zone(1000),
        "acst" | "sast" | "cast" => Token::Zone(930),
        "mt" => Token::Zone(830),
        "awst" | "cct" | "wadt" | "wst" => Token::Zone(800),
        "jt" => Token::Zone(730),
        "wast" => Token::Zone(700),
        "it" => Token::Zone(330),
        "bt" | "eetdst" => Token::Zone(300),
        "cetdst" | "eet" | "fwt" | "ist" | "mest" | "metdst" | "sst" => Token::Zone(200),
        "ndt" => Token::Zone(-230),
        "adt" => Token::Zone(-300),
        "nft" | "nst" => Token::Zone(-330),
        "hdt" => Token::Zone(-900),
        "ahst" | "cat" => Token::Zone(-1000),
        "nt" => Token::Zone(-1100),
        "sun" | "sun." | "sunday" | "mon" | "mon." | "monday" | "tue" | "tue." | "tues" | "tues." | "tuesday" | "wed" | "wed." | "wednesday" | "thu" | "thu." | "thurs" | "thurs." | "thursday" | "fri" | "fri." | "friday" | "sat" | "sat." | "saturday" => Token::Weekday,
        "jan" | "jan." | "january" => Token::Month(0),
        "feb" | "feb." | "february" => Token::Month(1),
        "mar" | "mar." | "march" => Token::Month(2),
        "apr" | "apr." | "april" => Token::Month(3),
        "may" => Token::Month(4),
        "ju" | "ju." | "jun" | "jun." | "june" => Token::Month(5),
        "jul" | "jul." | "july" => Token::Month(6),
        "aug" | "aug." | "august" => Token::Month(7),
        "sep" | "sep." | "sept" | "sept." | "september" => Token::Month(8),
        "oct" | "oct." | "october" => Token::Month(9),
        "nov" | "nov." | "november" => Token::Month(10),
        "dec" | "dec." | "december" => Token::Month(11),
        "am" => Token::Am,
        "pm" => Token::Pm,
        _ => return None,
    })
}
