[package]
name = "krkrz_tjs"
version.workspace = true
edition.workspace = true
license = "MIT AND BSD-3-Clause"

[dependencies]
anyhow.workspace = true
serde.workspace = true
krkrz_core.workspace = true
fancy-regex = "0.16.2"

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
